### ISSUE TITLE
FIX-BUILD: Build broken after PR #44

### ISSUE THREAD

**Issue by lemoine-agency-dev** [lemoine-agency/market-screener-froment#45]
Build broke after merging PR #44: fix: handle null current_price and pattern_annotations in signal detail

```
⚠ The "middleware" file convention is deprecated. Please use "proxy" instead. Learn more: https://nextjs.org/docs/messages/middleware-to-proxy
Failed to compile.

./src/app/api/v1/scans/[id]/signals/route.ts:26:33
Type error: Property 'errors' does not exist on type 'ZodError<{ id: string; }>'.

[0m [90m 24 |[39m   [36mif[39m ([33m![39mpathResult[33m.[39msuccess) {
 [90m 25 |[39m     [36mreturn[39m [33mNextResponse[39m[33m.[39mjson(
[31m[1m>[22m[39m[90m 26 |[39m       { error[33m:[39m pathResult[33m.[39merror[33m.[39merrors[[35m0[39m][33m.[39mmessage }[33m,[39m
 [90m    |[39m                                 [31m[1m^[22m[39m
 [90m 27 |[39m       { status[33m:[39m [35m400[39m }[33m,[39m
 [90m 28 |[39m     )
 [90m 29 |[39m   }[0m
Next.js build worker exited with code: 1 and signal: null
```

Fix the build error immediately.
